// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKiF3A5_rZUzELh4McsbvBUaB5EoUyU2A',
    appId: '1:840359679634:web:e5cb5eb9ab45759603f84b',
    messagingSenderId: '840359679634',
    projectId: 'paintingapp-286b2',
    authDomain: 'paintingapp-286b2.firebaseapp.com',
    storageBucket: 'paintingapp-286b2.appspot.com',
    measurementId: 'G-WRJFQHWF29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRiBkNpVmL4DWh3WV0FTzq6XcpqRWhrac',
    appId: '1:840359679634:android:a63752687dbb9cd903f84b',
    messagingSenderId: '840359679634',
    projectId: 'paintingapp-286b2',
    storageBucket: 'paintingapp-286b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmDMFQbL8O0SUusnmmHYF7mdZW_4Fq3-g',
    appId: '1:840359679634:ios:7da8d1917d56596003f84b',
    messagingSenderId: '840359679634',
    projectId: 'paintingapp-286b2',
    storageBucket: 'paintingapp-286b2.appspot.com',
    iosClientId: '840359679634-0f1hps76m2f5c68tv4t97lmm5mvub6if.apps.googleusercontent.com',
    iosBundleId: 'com.example.paintingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmDMFQbL8O0SUusnmmHYF7mdZW_4Fq3-g',
    appId: '1:840359679634:ios:7da8d1917d56596003f84b',
    messagingSenderId: '840359679634',
    projectId: 'paintingapp-286b2',
    storageBucket: 'paintingapp-286b2.appspot.com',
    iosClientId: '840359679634-0f1hps76m2f5c68tv4t97lmm5mvub6if.apps.googleusercontent.com',
    iosBundleId: 'com.example.paintingApp',
  );
}
